### ISSUE TITLE
Support advanced IPMI properties when enrolling hardware

### ISSUE THREAD

**Issue by msherman64** [ChameleonCloud/chi-in-a-box#223]
Add support for advanced IPMI properties when enrolling nodes.

Subtasks:
- [ ] https://github.com/ChameleonCloud/doni/issues/109
- [ ] https://github.com/ChameleonCloud/python-doniclient/issues/75
- [ ] Update Hardware Enrollment Docs
